# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine
WORKDIR /app
# Install dependencies without running prepare scripts
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts
# Copy source code
COPY . .
# Build the project
RUN npm run build
# Default command to start the MCP server
CMD ["node", "build/index.js"]
