# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies (including devDependencies for build)
COPY package*.json ./
RUN npm install

# Copy all other files
COPY . .

# Build the project and remove dev dependencies afterwards to slim down the image
RUN npm run build && npm prune --production

CMD ["node", "build/index.js"]
